### ISSUE TITLE
💄 linter error: Unexpected aliasing of 'this' to local variable

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/pacta-dashboard-svelte#102]
I have silenced the errors for now, but these lines are causing complaints:

https://github.com/RMI-PACTA/pacta-dashboard-svelte/blob/5e08a8f91624af3057a87fc30d21c98a89894cf8/src/js/pie_exploded.js#L235-L241

We should look into a solution (rather than just disabling the linter)

**Comment by cjyetman** [comment]
starting form here:
https://github.com/RMI-PACTA/pacta-dashboard-svelte/blob/e85aead84f71b0912ca1922ecace705181a1a8c8/src/js/pie_exploded.js#L235-L256

We can remove the `this` alias from the second level deep `.each()` like this (with a little bit of restructuring for better readability)

``` javascript
 textLabels.each(function () {
 	thisLabelDoc = d3.select(this);
 	y1 = thisLabelDoc.attr('y');

        thisLabel = this; // eslint-disable-line

 	textLabels.each(function () {
                thatLabelDoc = d3.select(this);
                y2 = thatLabelDoc.attr('y');

 		if (thisLabel == this) return;
 		if (thisLabelDoc.attr('text-anchor') != thatLabelDoc.attr('text-anchor')) return;

 		deltaY = y1 - y2;
 		if (Math.abs(deltaY) > minLabelSpacing) return;

 		again = true;
 		sign = deltaY > 0 ? 1 : -1;
 		adjustment = sign * alpha;
 		thisLabelDoc.attr('y', +y1 + adjustment);
 		thatLabelDoc.attr('y', +y2 - adjustment);
 	});
 });
```

I believe the intent of `if (thisLabel == this) return;` is to prevent the 2nd level deep function from comparing a label to itself, but it's harder to get rid of the 1st level deep `this` alias because you need it to compare to `this` in the 2nd level deep `.each()` function. Maybe we could work around that by comparing `thisLabelDoc` to `thatLabelDoc` instead with something like...

``` javascript
 textLabels.each(function () {
 	thisLabelDoc = d3.select(this);
 	y1 = thisLabelDoc.attr('y');

 	textLabels.each(function () {
                thatLabelDoc = d3.select(this);
                y2 = thatLabelDoc.attr('y');

 		if (thisLabelDoc == thatLabelDoc) return;
 		if (thisLabelDoc.attr('text-anchor') != thatLabelDoc.attr('text-anchor')) return;

 		deltaY = y1 - y2;
 		if (Math.abs(deltaY) > minLabelSpacing) return;

 		again = true;
 		sign = deltaY > 0 ? 1 : -1;
 		adjustment = sign * alpha;
 		thisLabelDoc.attr('y', +y1 + adjustment);
 		thatLabelDoc.attr('y', +y2 - adjustment);
 	});
 });
```

not exactly sure what an element of `textLabel` looks like though, especially since this `.each()` function is a jQuery function maybe?
