### ISSUE TITLE
feat: handle cases when parameter choices yield no plot in an elegant way

### ISSUE THREAD

**Issue by MonikaFu** [RMI-PACTA/pacta-dashboard-svelte#40]
Currently (for techmix but it will be implemented for other plots too) when the parameter choice yields no data an empty white rectangle is drawn in the div. This is not informative for the user. We should come up with a way to inform the user that the selection they made yields no data in an elegant way. 

Best to do this once the plots are wired up with all selectors and we do it consistently for all plots.

AB#11900

**Comment by jdhoffa** [comment]
Relates to https://dev.azure.com/RMI-PACTA/2DegreesInvesting/_backlogs/backlog/P4I/Features?workitem=11660

**Comment by jdhoffa** [comment]
For reference (and as of https://github.com/RMI-PACTA/pacta-dashboard-svelte/commit/c4bb90d40799ba78e77ec42933c1505ab80318a7):
I have noticed bizarre behaviour when the following takes place: 
- Select Sector Analysis
- Hit "Go" on default values (Power, Corporate Bonds)
- Select "Cement"

Observed behaviour: 
- "Scenario Source" options disappear
- All Power plots remain visible

Expected behaviour: 
- If no relevant data exists for Cement, I would expect that it shouldn't appear as a possible selection in the first place

**Comment by MonikaFu** [comment]
thanks @jdhoffa! The selection will still remain possible if there is data for cement within the other asset class as the options are the set of sectors that are relevant to at least one of the asset classes. It was a deliberate choice to implement it like that as we don't want to make the user choose first the asset class and then the sector but we want the sector and asset class choices to be on an equal level. This might yield an empty dataset, though if user selects a sector to which there is equity exposure but no bond exposure for example. 

I am thinking in the above case of disappearing the plots and selectors (apart from sector and asset class) and showing a message box asking to select different asset class or sector because there is no exposure in portfolio to this combination. It will also make more sense and be more visible to the user when I the summary statistics in the top right corner are implemented because then user will be able to see that, for example, exposure to bonds is X% but exposure to cement within bonds is 0%. So it will be clear that they should change the sector if they are interested in bonds results or change the asset class if they want to see their cement results.

**Comment by MonikaFu** [comment]
it's been done in #65
