### ISSUE TITLE
y axis title should be visible for each sector

### ISSUE THREAD

**Issue by MonikaFu** [RMI-PACTA/pacta-dashboard-svelte#87]
Currently for aviation:

![image](https://github.com/user-attachments/assets/9cf076ec-e3f8-4741-9839-5b14c20e9d76)

Increase plot height to fit the text.

AB#12272

**Comment by cjyetman** [comment]
The text for this y-axis label is baked into the data, e.g. here https://github.com/RMI-PACTA/pacta-dashboard-svelte/blob/e3f8f5ac01fe4d46321e9febe38a3ed17b889d75/sample-data/data_emissions.json#L715

@jdhoffa suggested that rather than increasing the height of the plot, that I break the text into two lines so that it fits. In principal, that seems to be the safest thing to do, especially since the text comes from the data, so the plot ideally should be able to recognize that whatever text it is told to put there, it should automatically break it into multiple lines if it's not going to fit.

Doing that though, is more complicated than it may seem... the plot code would need to estimate the space needed, if the text is too big then it would need to parse the text and find the appropriate place to split it (e.g. at the closest space, or breaking a long word with a hyphen), then add a newline/s where appropriate and adjust the baseline so the new lines do not overlap the plot.

An easier solution would be to modify the data in the text beforehand by adding a newline when/where appropriate in workflow.pacta.dashboard, though the plot might still have to adjust the baseline appropriately, e.g. if it detects one or more newline characters in the text.

The easiest solution would be to just bump the plot height a bit, especially seeing that only the last character is partially cut off, so we likely only need a few extra pixels.

Does that change your opinion at all @jdhoffa?

**Comment by MonikaFu** [comment]
Indeed, splitting the next is non-trivial and adding a new line in the text does not work for text within svgs. We would need to append two separate lines of text to svg instead of one in case the text is too long and find some sensible way of telling where the text should be split. I think that insteasing the height of the plot is currently the best solution, especially because the units are hard-coded so we know exactly how long the longest label will be.
