### ISSUE TITLE
Techmix company: make footnote data-driven

### ISSUE THREAD

**Issue by MonikaFu** [RMI-PACTA/pacta-dashboard-svelte#93]
Is seems to always say '1.5 scenario' even when chosen scenario is a different one.

![image](https://github.com/user-attachments/assets/16b3dc9a-1951-4f35-940a-262c4d5b2fda)

AB#12278

**Comment by cjyetman** [comment]
Logically, I think that `data_up` in the following code should probably be `subdata_up` (technically, in both locations), because `subdata_up` is a filtered version of `data_up` taking into account the selectors. There's also `data_down` and `subdata_down`, which I think are the "decreasing" techs, while the `up`'s are increasing techs. Seems at least possible that one could end up with only decreasing techs, and then `data_up`/`subdata_up` might have no data, so I can imagine it would be safer to use a combination of `subdata_up` and `subdata_down`... but "have no data" in this case might mean the values are 0 and therefore the scenario values are still there and it doesn't really matter which one you use. 

https://github.com/RMI-PACTA/pacta-dashboard-svelte/blob/ed95a2ba311d79c0b2783726e29da2070b6987d0/src/js/techexposure_company.js#L292-L297

**Comment by jdhoffa** [comment]
> ⚠️ note that @jdhoffa [tested this](https://github.com/RMI-PACTA/pacta-dashboard-svelte/pull/105#issuecomment-2514062528) and it resulted in `undefined` showing in the text instead of a scenario name (at least in some combination of input)

For posterity, I tested it against every combination of Sector and Asset type (from the test data), and it indicated `undefined` for all
